import { motion } from 'framer-motion'
import Head from 'next/head'
import { fadeInUp, routeAnimation } from '../animations'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div className="flex flex-col flex-grow" variants={routeAnimation} initial="initial" animate="animate"> 
        
        <div className="overflow-x-auto">
          <h1 className="text-2xl font-bold text-center text-blue-600">A propos de moi</h1>
          <div className="flex items-center justify-center overflow-hidden font-sans min-w-screen">
            <div className="w-full lg:w-5/6">
              <div className="rounded shadow-inner">
                <motion.div className="items-center justify-center p-12" initial="initial" animate="animate" variants={fadeInUp}>
                  <h5 className="my-3 font-medium">Bonjour et bienvenue sur mon portfolio !</h5>
                  <h5 className="my-3 font-medium">Ayant terminer ma formation de développeur web au sein de <strong>l'institut Paul Hankar</strong> à Bruxelles, je maitrise les langages <strong>HTML</strong>, <strong>CSS</strong>, <strong>Javascript</strong>, <strong>PHP</strong> et <strong>MySQL</strong> ainsi que la librairie <strong>React js</strong>. Je recherche actuellement un poste dans le domaine en tant que développeur web</h5>
                  <h5 className="my-3 font-medium">Vous verrez dans ce portfolio, mes compétences, mon parcours et tous les projets que j'ai pu réaliser.</h5>
                  <h5>Je suis dans l'attente d'opportunités en développement de site et application web. Particulièrement intéressé par le développement en langage JavaScript et ses librairies.</h5>
                </motion.div>
              </div>
            </div>
          </div>
        </div>
      </motion.div> 
    </div>
  )
}
